DATA_SOURCE = "snowflake"

[snowflake]
account = "uec27460.us-east-1"
user = "STREAMLIT_APP_USER"
password = "VeryStrongRandomPassword123!"
role = "BI_READERS"
warehouse = "COMPUTE_WH"
database = "NARS"
schema = "PROCESSED"
