DATA_SOURCE = "snowflake"

[snowflake]
account = "uec27460.us-east-1"
user = "radolfson"
password = "River.Stonefield_9285!Harbor"
role = "ACCOUNTADMIN"
warehouse = "COMPUTE_WH"
database = "NARS"
schema = "PROCESSED"
